// Autogenerated by geninfo.sh, do not edit

package gcewing.sg;

public class Info {
	static final String modName = "SG Craft";
	static final String modID = "SGCraft";
	static final String modPackage = "sg";
	static final String versionNumber = "0.5.2";
	static final String versionBounds = "[0.5,0.6)";
}
